SECTOR_MAP = {
    1: 'ADMINISTRACION',
    2: 'ALMACEN',
    3: 'LOGISTICA',
    4: 'CALIDAD',
    5: 'PRODUCCION'
}


ROLE_MAP = {
    1: 'ADMIN',
    2: 'VENDEDOR',
    3: 'OPERARIO',
    4: 'SUPERVISOR',
    5: 'SUPERVISOR_CALIDAD',
    6: 'RRHH',
    7: 'GERENTE',
    8: 'IT'
}

CANONICAL_PERMISSION_MAP = {
    'crear_usuarios': ['ADMIN', 'IT'],
    'modificar_usuarios': ['ADMIN', 'IT'],
    'inactivar_usuarios': ['ADMIN', 'RRHH'],
    'asignar_roles_permisos': ['ADMIN', 'IT'],
    'config_param_sistema': ['ADMIN', 'IT'],
    'solicitar_permisos': ['ADMIN', 'OPERARIO', 'SUPERVISOR', 'RRHH', 'IT'],
    'actualizar_lista_precios_prov': ['ADMIN'],
    'autenticacion': ['ADMIN', 'OPERARIO', 'SUPERVISOR', 'GERENTE'],
    'gestionar_proveedores': ['ADMIN'],
    'registrar_ingresos_stock': ['ADMIN', 'SUPERVISOR'],
    'recepcionar_compras': ['ADMIN'],
    'revision_final_recepcion': ['ADMIN', 'SUPERVISOR_CALIDAD'],
    'ver_reportes_basicos': ['VENDEDOR', 'OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'ver_reportes_produccion': ['VENDEDOR', 'SUPERVISOR', 'GERENTE'],
    'ver_indicadores_eficiencia': ['VENDEDOR', 'SUPERVISOR', 'GERENTE'],
    'ver_reportes_stock': ['VENDEDOR', 'SUPERVISOR', 'GERENTE'],
    'ver_reportes_financieros': ['VENDEDOR', 'GERENTE'],
    'exportar_reportes': ['VENDEDOR', 'SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'ver_dashboard': ['VENDEDOR', 'OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'actualizar_precios_proveedor': ['VENDEDOR'],
    'ver_materias_primas': ['VENDEDOR', 'OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'ver_stock_actual': ['VENDEDOR', 'OPERARIO', 'SUPERVISOR', 'GERENTE'],
    'ver_alertas_stock': ['VENDEDOR', 'OPERARIO', 'SUPERVISOR', 'GERENTE'],
    'ver_ordenes_compra': ['VENDEDOR', 'SUPERVISOR', 'GERENTE'],
    'crear_ordenes_compra': ['VENDEDOR', 'GERENTE'],
    'modificar_ordenes_compra': ['VENDEDOR', 'GERENTE'],
    'cancelar_ordenes_compra': ['VENDEDOR', 'GERENTE'],
    'ver_ordenes_venta': ['VENDEDOR', 'GERENTE'],
    'crear_ordenes_venta': ['VENDEDOR', 'GERENTE'],
    'modificar_ordenes_venta': ['VENDEDOR', 'GERENTE'],
    'cancelar_ordenes_venta': ['VENDEDOR', 'GERENTE'],
    'registrar_envios': ['VENDEDOR', 'SUPERVISOR'],
    'registrar_datos_calidad_basicos': ['OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'ver_ordenes_produccion': ['OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'iniciar_produccion': ['OPERARIO', 'SUPERVISOR'],
    'registrar_inicio_etapa': ['OPERARIO', 'SUPERVISOR'],
    'registrar_fin_etapa': ['OPERARIO', 'SUPERVISOR'],
    'registrar_desperdicios': ['OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'ver_progreso_tiempo_real': ['OPERARIO', 'SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'ver_info_empleados': ['SUPERVISOR', 'RRHH', 'GERENTE'],
    'registrar_asistencias': ['SUPERVISOR', 'RRHH'],
    'gestionar_turnos': ['SUPERVISOR', 'RRHH', 'GERENTE'],
    'aprobar_permisos': ['SUPERVISOR', 'RRHH', 'GERENTE'],
    'ver_consumo_materias_primas': ['SUPERVISOR', 'GERENTE'],
    'ver_indicadores_desperdicio': ['SUPERVISOR', 'GERENTE'],
    'config_param_negocio': ['SUPERVISOR', 'GERENTE', 'IT'],
    'crear_materias_primas': ['SUPERVISOR', 'GERENTE'],
    'modificar_materias_primas': ['SUPERVISOR', 'GERENTE'],
    'eliminar_materias_primas': ['SUPERVISOR', 'GERENTE'],
    'registrar_egresos_stock': ['SUPERVISOR'],
    'config_alertas_stock': ['SUPERVISOR', 'GERENTE'],
    'gestionar_lotes_vencimientos': ['SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'asignar_materias_primas_ordenes': ['SUPERVISOR'],
    'config_umbrales_stock': ['SUPERVISOR'],
    'crear_ordenes_compra_manual': ['SUPERVISOR'],
    'realizar_control_calidad': ['SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'aprobar_lotes': ['SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'rechazar_lotes': ['SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'ver_historial_controles': ['SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'registrar_no_conformidades': ['SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'ver_calidad_insumos': ['SUPERVISOR', 'SUPERVISOR_CALIDAD', 'GERENTE'],
    'crear_ordenes_produccion': ['SUPERVISOR', 'GERENTE'],
    'modificar_ordenes_produccion': ['SUPERVISOR', 'GERENTE'],
    'aprobar_ordenes_produccion': ['SUPERVISOR', 'GERENTE'],
    'cancelar_ordenes_produccion': ['SUPERVISOR', 'GERENTE'],
    'pausar_produccion': ['SUPERVISOR'],
    'modificar_registros_historicos': ['SUPERVISOR'],
    'control_calidad_lote': ['SUPERVISOR', 'SUPERVISOR_CALIDAD'],
    'aprobar_rechazar_lotes': ['SUPERVISOR'],
    'config_modos_linea': ['SUPERVISOR'],
    'config_param_calidad': ['SUPERVISOR_CALIDAD', 'GERENTE'],
    'modificar_info_empleados': ['RRHH', 'GERENTE'],
    'monitoreo_tecnico_ver_logs': ['GERENTE', 'IT'],
    'ver_reportes_estrategicos': ['GERENTE'],
    'inactivar_proveedores_clientes': ['GERENTE'],
    'aprobar_ordenes_compra': ['GERENTE'],
    'aprobar_ordenes_venta': ['GERENTE'],
    'gestionar_backups': ['IT']
}

def get_allowed_roles_for_action(action_name):
    """
    Devuelve la lista de roles permitidos para una acción específica.
    """
    return CANONICAL_PERMISSION_MAP.get(action_name, [])