from app.models.base_model import BaseModel

class PagoModel(BaseModel):
    def __init__(self):
        super().__init__()
        self.table_name = 'pagos'
        self.id_field = 'id_pago'
        self.columns = {
            'id_pago': 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'id_pedido': 'BIGINT',
            'fecha': 'TIMESTAMP WITH TIME ZONE',
            'monto': 'DECIMAL',
            'metodo_pago': 'VARCHAR',
            'datos_adicionales': 'TEXT',
            'comprobante_url': 'VARCHAR',
            'estado': 'VARCHAR',
            'id_usuario_registro': 'INTEGER'
        }

    def get_table_name(self):
        return 'pagos'

    def get_pagos_by_pedido_id(self, id_pedido):
        return self.find_all({'id_pedido': id_pedido})

